package com.olenick.avatar.reports;

/**
 * FeatureExecutor event.
 */
public enum FeatureExecutorEvent {
    FEATURE_STARTED, FEATURE_FAILED, FEATURE_ENDED, SCENARIO_STARTED, SCENARIO_ENDED, LOGIN_PAGE_STARTED, LOGIN_PAGE_ENDED, PATIENT_EXPERIENCE_STARTED, PATIENT_EXPERIENCE_ENDED, REPORT_TAB_STARTED, REPORT_TAB_ENDED, REPORT_TAB_EXPORT_TO_PDF_STARTED, REPORT_TAB_EXPORT_TO_PDF_ENDED, SCENARIO_FAILED, WARNING
}
